name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Étape pour installer Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh
          export PATH=$PATH:$HOME/.railway/bin

      # Étape pour définir le token en tant que variable d'environnement
      - name: Set Railway API Token
        run: |
          echo "RAILWAY_API_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      # Étape pour déployer l'application
      - name: Deploy to Railway
        run: |
          railway up

