name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Installer la version mise à jour de Railway CLI via npm
      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli

      # Authentification avec Railway via le token d'API
      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Utilise le secret correctement
        run: |
          railway login --apiKey $RAILWAY_TOKEN

      # Déployer l'application sur Railway
      - name: Deploy to Railway
        run: |
          railway up
