name: Deploy to Railway

on:
  push:
    branches:
      - main  # Le déploiement se déclenche à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Le workflow s'exécute sur un environnement Linux (Ubuntu)

    steps:
  - uses: actions/checkout@v3
  - name: Deploy to Railway
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    run: |
      railway up
