name: Deploy to Railway

on:
  push:
    branches: [main]  # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    container: ghcr.io/railwayapp/cli:latest  # Use the Railway CLI container

    env:
      SVC_ID: dc69626d-0430-4b93-a579-b23dd48ddebc  # Replace with your actual service ID
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Use the RAILWAY_TOKEN secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}  # Deploy to Railway using the service ID


