name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Railway CLI
        run: |
          curl -sSL https://railway.app/cli.sh | sh
      - name: Login to Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}
      - name: Deploy to Railway
        run: railway up --projectId ${{ secrets.RAILWAY_PROJECT_ID }}
