name: Deploy to Railway

on:
  push:
    branches:
      - main  # Déclenchement sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour exécuter les commandes

    steps:
      # Étape 1 : Cloner le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer curl et bash si nécessaires
      - name: Install bash and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y bash curl

      # Étape 3 : Installer le Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/cli.sh -o railway.sh  # Télécharge le script Railway CLI
          chmod +x railway.sh  # Rend le script exécutable
          ./railway.sh  # Exécute le script

      # Étape 4 : Déploiement sur Railway
      - name: Deploy to Railway
        run: |
          railway up  # Déploiement sur Railway
