name: Deploy to Railway

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Exécute le job sur un environnement Ubuntu Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code source du dépôt GitHub

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh  # Installe Railway CLI
          echo "$HOME/.railway/bin" >> $GITHUB_PATH  # Ajoute Railway CLI au PATH

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Utilisation du token Railway stocké dans GitHub Secrets
        run: |
          railway up --service "service web"  # Déploie l'application sur Railway en précisant le service



