name: Deploy to Railway

on:
  push:
    branches:
      - main  # Déploiement déclenché par un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Environnement Linux (Ubuntu) pour l'exécution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Télécharge le code depuis GitHub

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH=$HOME/.railway/bin:$PATH

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Utilisation du token pour l'authentification
        run: |
          railway up --service "service web"  # Utilisation du nom exact du service entre guillemets


