name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Étape pour installer Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh
          export PATH=$PATH:$HOME/.railway/bin

      # Étape pour se connecter à Railway via l'API Token
      - name: Login to Railway
        run: |
          echo ${{ secrets.RAILWAY_TOKEN }} | railway login --token

      # Étape pour déployer l'application
      - name: Deploy to Railway
        run: |
          railway up








