name: Deploy to Railway

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Exécute le job sur un environnement Ubuntu Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code source du dépôt GitHub

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh  # Installe Railway CLI
          export PATH=$HOME/.railway/bin:$PATH  # Ajoute Railway CLI au PATH

      - name: Authenticate with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Utilisation du token Railway stocké dans GitHub Secrets
        run: |
          railway login --token "$RAILWAY_TOKEN"  # Authentification avec le token sécurisé

      - name: Deploy to Railway
        run: |
          railway up  # Déploie l'application sur Railway



